##
# docker-compose extra services
# These services are completely optional, as they arent required to operate
# from the base yaml file.
##

##
# Let's Encrypt Certbot
# This service provides free SSL certificates that can be used to connect to the world. 
# Uncomment if you are using the panel on its own (without a reverse proxy). It is 
# recommended to use the webroot plugin. To get a certificate, run "docker-compose 
# run --rm certbot --webroot -w /etc/letsencrypt/webroot -d {domain}" and follow
# the instructions on screen. 
##
certbot:
  command: renew
  image: certbot/certbot
  volumes:
  - ./letsencrypt:/etc/letsencrypt
# If you are using the certbot container, apply this to the panel container
panel:
  volumes:
  - ./letsencrypt:/etc/letsencrypt
  - ./letsencrypt/webroot/.well-known:/var/www/html/public/.well-known

##
# Seperate Worker Container
# If you plan on using another container for handling all the workers and cronjobs, 
# use these services and set DISABLE_WORKERS=true for the panel container
##
worker:
  command: php /var/www/html/artisan queue:work database --queue=high,standard,low --sleep=3 --tries=3
  env_file: .env
  image: quay.io/ccarney/pterodactyl-panel:latest
  restart: always
  volumes_from:
  - panel
cron:
  command: /usr/sbin/crond -f -l 0
  env_file: .env
  image: quay.io/ccarney/pterodactyl-panel:latest
  restart: always
  volumes_from:
  - panel

sftp:
  image: ccarney16/pterodactyl-sftp:v1.0.1
  restart: always
  volumes_from:
  - daemon