##
# Pterodactyl Panel Docker Setup by ccarney
##
version: '2.1'
services:
##
# MariaDB (MySQL) Server
# If you rely on another MySQL/MariaDB instance, 
# this can be safely removed. If you want to have 
# your game servers be able to access this, be sure 
# to declare your ports.
##
  mysql:
    env_file: .env
    image: mariadb:10.2
    restart: always
    volumes:
    - ./db:/var/lib/mysql

# Panel Cache
# This service is required for the panel to function.
# You can use either redis or memcached, but redis
# is provided by default here.
##
  cache:
    image: redis:alpine
    restart: always

##
# Pterodactyl Panel
# This is the main service that will be seen publically.
##
  panel:
    depends_on:
    - cache
    - mysql
    env_file: .env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes:
    - ./data:/data
    ports:
    - 80:80
    - 443:443

##
# Pterodactyl Daemon
# If you don't plan on running the daemon on the same machine, 
# you may comment/delete the section below.
##
  daemon:
    depends_on:
    - panel
    image: ccarney16/pterodactyl-daemon:latest
    ports:
    -  8080:8080
    privileged: true
    restart: always
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon-data:/srv/daemon-data

    - /tmp/pterodactyl:/tmp/pterodactyl

    - /etc/localtime:/etc/localtime

    # Docker socket and directory, needed to communicate to docker
    # NOTE: If you are using docker in a different directory, please change below to reflect that!
    - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
    - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
