###
# Daemon Configuration File
#
# This config only provides the daemon and certbot.
# Meant for multi machine network where a panel is already established.
###
version: "3.8"
services:
  ##
  # -- Let's Encrypt Certbot --
  ##
  certbot:
    command: renew
    image: docker.io/certbot/certbot:latest
    profiles: [ letsencrypt ]
    volumes:
      - ./conf.d/letsencrypt:/etc/letsencrypt
      - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
  ##
  # -- Pterodactyl Daemon --
  # This service provides the wings runtime.
  ##
  daemon:
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: docker.io/ccarney16/pterodactyl-daemon:${DAEMON_VERSION:-latest}
    ports:
      - 2022:2022
      - 8080:8080
    privileged: true
    profiles: [ daemon ]
    restart: always
    volumes:
      - ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}:${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - ./conf.d/daemon:/etc/pterodactyl
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d/certs:/etc/certs:ro
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
